# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20180730_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homemainshow',
            old_name='marketprice',
            new_name='marketprice1',
        ),
    ]
