# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='projectimg',
            new_name='productimg',
        ),
    ]
